
//IMPORTS REACT/NEXT DEPENDENCIES:

import Link from "next/link";
import Image from "next/image";
//IMPORTS EXT DEPENDENCIES:
import {Marcellus, Montserrat } from 'next/font/google';
import { motion, AnimatePresence } from 'framer-motion';
//IMPORTS GLOBAL STATES:
import GlobalStateContextProvider from "@/context/GlobalStateContext";
import { useGlobalState } from "@/context/GlobalStateContext";
import CursorProvider from "@/components/CursorContext";
//IMPORTS HOOKS:
//IMPORTS VARIANTS:
// import { fadeIn } from '@/lib/hero-variants';
//IMPORTS COMPONENTS:
import Header from "@/components/Header";
import Transition from "@/components/Transition";
//IMPORTS IMAGES:
//IMPORTS CSS:
//IMPORT ENV:
// import localFont from "next/font/local";
import "./globals.css";
import PageTransition from "@/components/PageTransition";

const marcellus = Marcellus({ 
  subsets: ['latin'], 
  weight: ['400'], 
  variable: '--font-marcellus'
});

const montserrat = Montserrat({ 
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
  variable: '--font-montserrat'
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalStateContextProvider>
      <html lang="en" className="h-screen">
        <body
          className={`${marcellus.variable} ${montserrat.variable} antialiased overflow-x-hidden`}
          style={{position: 'relative'}}
        >
          {/* <CursorProvider> */}
            <Transition />
            <Header />
            <PageTransition>
              {children}
            </PageTransition>
          {/* </CursorProvider> */}
        </body>
      </html>
    </GlobalStateContextProvider>
  );
}
